2024-05-29 16:48:55,927 INFO    MainThread:342755 [wandb_setup.py:_flush():76] Current SDK version is 0.16.0
2024-05-29 16:48:55,927 INFO    MainThread:342755 [wandb_setup.py:_flush():76] Configure stats pid to 342755
2024-05-29 16:48:55,927 INFO    MainThread:342755 [wandb_setup.py:_flush():76] Loading settings from /media/mountHDD2/duong/.config/wandb/settings
2024-05-29 16:48:55,927 INFO    MainThread:342755 [wandb_setup.py:_flush():76] Loading settings from /media/mountHDD2/duong/git/Segmentation/wandb/settings
2024-05-29 16:48:55,927 INFO    MainThread:342755 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-29 16:48:55,927 INFO    MainThread:342755 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-29 16:48:55,927 INFO    MainThread:342755 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': '/media/mountHDD2/duong/git/Segmentation/main.py', 'program': '/media/mountHDD2/duong/git/Segmentation/main.py'}
2024-05-29 16:48:55,927 INFO    MainThread:342755 [wandb_setup.py:_flush():76] Applying login settings: {'force': True}
2024-05-29 16:48:55,927 INFO    MainThread:342755 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-05-29 16:48:55,927 INFO    MainThread:342755 [wandb_init.py:_log_setup():524] Logging user logs to /media/mountHDD2/duong/git/Segmentation/wandb/run-20240529_164855-2hpkplk5/logs/debug.log
2024-05-29 16:48:55,927 INFO    MainThread:342755 [wandb_init.py:_log_setup():525] Logging internal logs to /media/mountHDD2/duong/git/Segmentation/wandb/run-20240529_164855-2hpkplk5/logs/debug-internal.log
2024-05-29 16:48:55,927 INFO    MainThread:342755 [wandb_init.py:init():564] calling init triggers
2024-05-29 16:48:55,927 INFO    MainThread:342755 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'ds': 'oxford', 'bs': 32, 'wk': 1, 'pm': False, 'sz': 256, 'aug': False, 'idx': 0, 'seed': 0, 'epochs': 100, 'model': 'unet', 'loss': '', 'test': False, 'wandb': False, 'log': True, 'init_ch': 32, 'seg_n_classes': 3, 'lr': 0.001}
2024-05-29 16:48:55,927 INFO    MainThread:342755 [wandb_init.py:init():614] starting backend
2024-05-29 16:48:55,927 INFO    MainThread:342755 [wandb_init.py:init():618] setting up manager
2024-05-29 16:48:55,930 INFO    MainThread:342755 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-29 16:48:55,947 INFO    MainThread:342755 [wandb_init.py:init():624] backend started and connected
2024-05-29 16:48:55,952 INFO    MainThread:342755 [wandb_init.py:init():716] updated telemetry
2024-05-29 16:48:55,956 INFO    MainThread:342755 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-05-29 16:48:56,507 ERROR   MainThread:342755 [wandb_init.py:init():775] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-05-29 16:48:56,693 ERROR   MainThread:342755 [wandb_init.py:init():1184] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/media/mountHDD2/duong/git/.env/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1166, in init
    run = wi.init()
  File "/media/mountHDD2/duong/git/.env/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-05-29 16:48:57,695 WARNING MsgRouterThr:342755 [router.py:message_loop():77] message_loop has been closed
